name: Auto Close Issues

on:
  issues:
    types: [labeled]
  workflow_dispatch:  # Allow manual triggering

jobs:
  auto-close:
    runs-on: ubuntu-latest
    # --- 添加这部分 ---
    permissions:
      issues: write # 授予修改 PR 的权限，包括添加审查者
    # ------------------
    if: contains(github.event.issue.labels.*.name, 'completed') || contains(github.event.issue.labels.*.name, 'wontfix')
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: |
            This issue has been automatically closed because it was labeled as '${{ contains(github.event.issue.labels.*.name, 'completed') && 'completed' || 'wontfix' }}'.
          token: ${{ secrets.GITHUB_TOKEN }}
