name: Auto close labeled issues

on:
  issues:
    types: [labeled, opened, edited, reopened]

permissions:
  issues: write

jobs:
  close:
    if: contains(github.event.issue.labels.*.name, 'completed') || contains(github.event.issue.labels.*.name, 'wontfix')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.payload.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: 'Closing automatically based on label.'
            });
            await github.rest.issues.update({
              owner,
              repo,
              issue_number,
              state: 'closed'
            });
